package senegai.server.exampledata.bo

import org.springframework.stereotype.Component
import senegai.server.exampledata.DataContext
import senegai.server.exampledata.framework.datafaker.FakerHelper
import senegai.server.service.bo.ArticulusInteriorBO

/**
 * Creates example data for the business object [ArticulusInteriorBO].
 *
 * A nested (leaf) item without further nested items or enums: it is generated by the same
 * `ItemExampleDataCreatorRenderer` as [SilvaOptionumExampleDataCreator] and therefore carries
 * no tavnit comments itself - it just shows the rendered result for a leaf item.
 */
@Component
class ArticulusInteriorExampleDataCreator {

    fun create(dataContext: DataContext): ArticulusInteriorBO = ArticulusInteriorBO(
        scriptumTriviale = FakerHelper.randomString(dataContext),
        numerusStupidus = FakerHelper.randomInt(dataContext),
    )

    fun createList(dataContext: DataContext, size: Int): List<ArticulusInteriorBO> =
        List( size = size) { create(dataContext) }
}
