package senegai.server.exampledata.bo

import org.springframework.stereotype.Component
import senegai.server.service.bo.ArticulusInteriorBO

/**
 * Creates example data for the business object [ArticulusInteriorBO].
 *
 * A nested (leaf) item without further nested items or enums: it is generated by the same
 * `ItemExampleDataCreatorRenderer` as [SilvaOptionumExampleDataCreator] and therefore carries
 * no tavnit comments itself - it just shows the rendered result for a leaf item.
 */
@Component
class ArticulusInteriorExampleDataCreator {

    /** A single fully populated example aggregate. */
    fun create(): ArticulusInteriorBO = ArticulusInteriorBO(
        scriptumTriviale = "exemplum",
        numerusStupidus = 42,
    )

    /** A list of distinct example aggregates. */
    fun createList(): List<ArticulusInteriorBO> = listOf(
        create(),
        create(),
        create(),
    )
}
