package senegai.codegen.renderer.model.be

import senegai.codegen.renderer.NotSupportedInTemplateException
import senegai.codegen.renderer.model.NameCase
import senegai.codegen.renderer.model.db.DbTableModel
import senegai.model.schema.BuiltInType
import senegai.model.schema.ItemId

data class BeItemModel(
    val itemDescription: BeItemDescriptionModel,
    val attributes: List<BeAttributeModel>,
    /**
     * The attribute that identifies this item (its primary key), or `null` if this item
     * has none. It is always a plain built-in attribute, never a reference to another item.
     */
    val idAttribute: BuiltInTypeBeAttributeModel?,
    /** The table this item is stored in, or `null` if it has no primary key and is therefore nested. */
    val dbTable: DbTableModel?,
) {
    val itemId: ItemId = itemDescription.itemId
    val itemName: NameCase = itemDescription.itemName

    /** Whether this item is identified by a primary key and can therefore be addressed, searched and referenced. */
    val hasPrimaryKey: Boolean = idAttribute != null

    /**
     * The primary key, for the templates that are only rendered for an item that has one
     * (controller, service, repository, search, by-ids, example data initializer).
     */
    val primaryKeyAttribute: BuiltInTypeBeAttributeModel
        get() = requireNotNull(idAttribute) {
            "The item '${itemName.pascalCase}' declares no primary key."
        }

    /**
     * The table this item is stored in, for the templates that are only rendered for an item
     * that has a primary key.
     */
    val table: DbTableModel
        get() = requireNotNull(dbTable) {
            "The item '${itemName.pascalCase}' is stored in no table, because it declares no primary key."
        }

    /** Whether the primary key is a [BuiltInType.UUID], e.g. to render the import of the UUID type. */
    val hasUuidPrimaryKey: Boolean = idAttribute?.builtInType == BuiltInType.UUID

    val hasNumberPrimaryKey: Boolean = idAttribute?.builtInType == BuiltInType.NUMBER

    /**
     * Whether the repository hands out the primary key of a newly created item. A
     * [BuiltInType.STRING] key is supplied by the caller instead, so no `nextId()` exists for it.
     */
    val hasGeneratedPrimaryKey: Boolean = hasUuidPrimaryKey || hasNumberPrimaryKey

    /**
     * The Kotlin expression that hands out the next unused primary key, rendered into the
     * `nextId()` of the in-memory repository, the only place that assigns one.
     *
     * A NUMBER key counts up and therefore reads the `store` map the in-memory repository
     * holds its entries in. A STRING key is supplied by the caller, so it is never handed out.
     */
    val nextPrimaryKeyValueExpression: String
        get() = when (primaryKeyAttribute.builtInType) {
            BuiltInType.UUID -> "UUID.randomUUID()"
            BuiltInType.NUMBER -> "(store.keys.maxOrNull() ?: 0) + 1"
            BuiltInType.STRING -> throw NotSupportedInTemplateException(clientProvidedPrimaryKeyMessage())
            BuiltInType.DOUBLE, BuiltInType.BOOLEAN ->
                throw NotSupportedInTemplateException(unsupportedPrimaryKeyTypeMessage())
        }

    /**
     * The counterpart of [nextPrimaryKeyValueExpression] for a repository backed by a database.
     *
     * A NUMBER key is handed out by the sequence PostgreSQL created for the key column itself,
     * looked up at runtime so that no sequence name has to be spelled out here. It requires the
     * column to be declared `GENERATED BY DEFAULT AS IDENTITY`, never `ALWAYS`, because the
     * repository writes the key explicitly in its INSERT.
     *
     * `pg_get_serial_sequence` reads its first argument as an identifier and therefore folds it
     * to lower case itself, but takes the second one as a plain string that it never folds — so
     * the column name has to be lowercased here to match the one an unquoted CREATE TABLE stored.
     */
    val databaseNextPrimaryKeyValueExpression: String
        get() = when (primaryKeyAttribute.builtInType) {
            BuiltInType.UUID -> "UUID.randomUUID()"
            BuiltInType.NUMBER ->
                "jdbcClient.sql(\"SELECT nextval(pg_get_serial_sequence('\$TABLE_NAME', " +
                        "'\${PRIMARY_KEY_COLUMN_NAME.lowercase()}'))\").query(Int::class.java).single()"
            BuiltInType.STRING -> throw NotSupportedInTemplateException(clientProvidedPrimaryKeyMessage())
            BuiltInType.DOUBLE, BuiltInType.BOOLEAN ->
                throw NotSupportedInTemplateException(unsupportedPrimaryKeyTypeMessage())
        }

    /**
     * The Kotlin expression for a primary key no item is ever identified by, rendered
     * wherever a reference has to be created although there is nothing to reference yet.
     */
    val unresolvablePrimaryKeyValueExpression: String
        get() = when (primaryKeyAttribute.builtInType) {
            BuiltInType.UUID -> "UUID(0L, 0L)"
            BuiltInType.STRING -> "\"\""
            BuiltInType.NUMBER -> "0"
            BuiltInType.DOUBLE, BuiltInType.BOOLEAN ->
                throw NotSupportedInTemplateException(unsupportedPrimaryKeyTypeMessage())
        }

    private fun clientProvidedPrimaryKeyMessage(): String =
        "The item '${itemName.pascalCase}' is identified by the attribute " +
                "'${primaryKeyAttribute.attributeName.camelCase}' of the built-in type " +
                "${primaryKeyAttribute.builtInType}, which is supplied by the caller and never handed out."

    private fun unsupportedPrimaryKeyTypeMessage(): String =
        "The item '${itemName.pascalCase}' is identified by the attribute " +
                "'${primaryKeyAttribute.attributeName.camelCase}' of the built-in type " +
                "${primaryKeyAttribute.builtInType}, which no item can be identified by."

    val usedEnums: List<BeEnumModel> = attributes
        .filterIsInstance<EnumBeAttributeModel>()
        .map { it.enum }
        .distinct()

    val attributesWithItemType: List<ItemBeIAttributeModel> = attributes
        .filterIsInstance<ItemBeIAttributeModel>()

    val attributesWithEnumType: List<EnumBeAttributeModel> = attributes
        .filterIsInstance<EnumBeAttributeModel>()

    val builtInAttributes: List<BuiltInTypeBeAttributeModel> = attributes
        .filterIsInstance<BuiltInTypeBeAttributeModel>()

    /**
     * All attributes referencing another item. They are a subset of [builtInAttributes],
     * as a reference is transported as the primary key of the referenced item.
     */
    val attributesWithItemReference: List<ItemReferenceBeAttributeModel> = attributes
        .filterIsInstance<ItemReferenceBeAttributeModel>()

    /** All items referenced by an attribute of this item, e.g. to inject one example data fetcher per item. */
    val referencedItems: List<BeReferencedItemModel> = attributesWithItemReference
        .map { it.referencedItem }
        .distinct()

    val builtInTypeAndEnumAttributes: List<BeAttributeModel> = attributes
        .filter { it.isBuiltIn || it.isEnum }

    val directlyNestedItems: List<BeItemDescriptionModel> = attributes
        .filterIsInstance<ItemBeIAttributeModel>()
        .map { it.referencedItem }
        .distinct()

    /**
     * Item references are left out: their example data is not generated but fetched from the
     * already existing instances of the referenced item.
     */
    val exampleDataGeneratorConfigs: List<BeExampleDataGeneratorConfig> = attributes
        .filterIsInstance<BuiltInTypeBeAttributeModel>()
        .filter { !it.isItemReference }
        .map { it.exampleDataGeneratorConfig }
        .distinctBy { it.fullQualifiedName }

    /**
     * UUIDs are edited with the very same text input as strings, therefore they count
     * as text attributes for everything that is about rendering an input field.
     */
    val containsTextAttributes: Boolean = attributesOfTypes(TEXT_LIKE_BUILT_IN_TYPES, isList = false).any()
    val containsBooleanAttributes: Boolean = attributesOfType(BuiltInType.BOOLEAN, isList = false).any()
    val containsNumberAttributes: Boolean = attributesOfTypes(NUMBER_LIKE_BUILT_IN_TYPES, isList = false).any()

    val containsTextListAttributes: Boolean = attributesOfTypes(TEXT_LIKE_BUILT_IN_TYPES, isList = true).any()
    val containsBooleanListAttributes: Boolean = attributesOfType(BuiltInType.BOOLEAN, isList = true).any()
    val containsNumberListAttributes: Boolean = attributesOfTypes(NUMBER_LIKE_BUILT_IN_TYPES, isList = true).any()

    /**
     * Whether any attribute is a [BuiltInType.UUID], e.g. to render the import of the UUID
     * type. A reference counts here if the item it references is identified by a UUID.
     */
    val containsUuidAttributes: Boolean = attributesOfTypes(setOf(BuiltInType.UUID)).any()

    private fun attributesOfType(filterBuiltInType: BuiltInType, isList: Boolean): List<BeAttributeModel> =
        attributesOfTypes(setOf(filterBuiltInType), isList)

    /** All built-in attributes of one of the [filterBuiltInTypes], of any cardinality if [isList] is `null`. */
    private fun attributesOfTypes(filterBuiltInTypes: Set<BuiltInType>, isList: Boolean? = null): List<BeAttributeModel> {
        return attributes
            .filterIsInstance<BuiltInTypeBeAttributeModel>()
            .filter { it.builtInType in filterBuiltInTypes && (isList == null || it.isList == isList) }
    }

    private companion object {
        /** Built-in types that are rendered as a text input on the client. */
        private val TEXT_LIKE_BUILT_IN_TYPES = setOf(BuiltInType.STRING, BuiltInType.UUID)

        /** Built-in types that are rendered as a number input on the client. */
        private val NUMBER_LIKE_BUILT_IN_TYPES = setOf(BuiltInType.NUMBER, BuiltInType.DOUBLE)
    }
}
