/* @tt{{{

    @template-renderer [
        templateRendererClassName="ItemTableSchemaRenderer"
        templateRendererPackageName="senegai.codegen.renderer.db"
        templateRendererInterfaceName="DbItemRenderer"
        templateRendererInterfacePackageName="senegai.codegen.renderer.db"
    ] [
        modelClassName="DbTableModel"
        modelPackageName="senegai.codegen.renderer.model.db"
        modelName="model"
    ]

    @replace-value-by-expression
        [ searchValue="SILVA_OPTIONUM" replaceByExpression="model.tableName" ]

    @replace-value-by-value
        [ searchValue="V00001__schema_" replaceByValue="R__schema_" ]
    @modify-provided-filepath-by-replacements
    @end-replace-value-by-value

}}}@ */
DROP TABLE IF EXISTS SILVA_OPTIONUM CASCADE;

CREATE TABLE SILVA_OPTIONUM (
    /* @tt{{{
        @foreach [ iteratorExpression="model.columns" loopVariable="column" ]
        @if [ conditionExpression="column.isNullable" ]
        @replace-value-by-expression
            [ searchValue="ARTICULUS_INTERIOR_SINGULARIS_OPTIONALIS" replaceByExpression="column.columnName" ]
            [ searchValue="jsonb" replaceByExpression="column.sqlTypeName" ]
    }}}@ */
    ARTICULUS_INTERIOR_SINGULARIS_OPTIONALIS jsonb,
    /* @tt{{{
        @end-replace-value-by-expression
        @else
        @replace-value-by-expression
            [ searchValue="APPELLATIO" replaceByExpression="column.columnName" ]
            [ searchValue="appellatio_comis" replaceByExpression="column.sqlTypeName" ]
    }}}@ */
    APPELLATIO appellatio_comis/* @tt{{{ @if [ conditionExpression="column.isIdentity" ] @print-text [ text=" GENERATED BY DEFAULT AS IDENTITY" ] @end-if }}}@ */ NOT NULL,
    /* @tt{{{   @end-replace-value-by-expression @end-if @end-foreach @ignore-text  }}}@ */
    INDEX_UNICUS                             uuid    NOT NULL,
    CAMPUS_TEXTUS_OBLIGATORIUS               text    NOT NULL,
    CAMPUS_TEXTUS_OPTIONALIS                 text,
    ARTICULUS_INTERIOR_SINGULARIS            jsonb   NOT NULL,
    ARTICULUS_INTERIOR_ITERATUS              jsonb   NOT NULL,
    ARTICULUS_INTERIOR_OPTIONALIS_ITERATUS   jsonb,
    APPELLATIO_OPTIONALIS_ITERATUS           jsonb,
    CAMPUS_DIEI                              date,
    CAMPUS_BIVALENS                          boolean NOT NULL,
    CAMPUS_NUMERORUM                         integer NOT NULL,
    ITERATIO_SIMPLICIUM_TEXTUUM              jsonb   NOT NULL,
    RELATIO_AD_ENTITATEM_OPTIONALIS_ITERATUS jsonb,
    RELATIO_AD_ENTITATEM_OPTIONALIS          uuid,
    /* @tt{{{   @end-ignore-text  }}}@ */
    /* @tt{{{
        @replace-value-by-expression
            [ searchValue="INDEX_UNICUS" replaceByExpression="model.primaryKeyColumn.columnName" ]
    }}}@ */
    PRIMARY KEY (INDEX_UNICUS)
    /* @tt{{{   @end-replace-value-by-expression  }}}@ */
);
