/*
 * This file is generated using tavnit.
 */
package senegai.codegen.renderer.db

import senegai.codegen.renderer.model.db.DbTableModel

/**
 * Generate the content for the template `ItemTableSchemaRenderer`.
 *
 * This template renderer was generated from the template:
 * - file: `R__schema_SILVA_OPTIONUM.sql`
 * - path: `R__schema_SILVA_OPTIONUM.sql`
 */
object ItemTableSchemaRenderer : DbItemRenderer {

    override fun renderTemplate(model: DbTableModel): String {
        return """
          |DROP TABLE IF EXISTS ${model.tableName} CASCADE;
          |
          |CREATE TABLE ${model.tableName} (
          |${ model.columns.joinToString("") { column ->  """${ if(column.isNullable) { """    ${column.columnName} ${column.sqlTypeName},
                  |""" } else { """    ${column.columnName} ${column.sqlTypeName}${ if(column.isIdentity) { """ GENERATED BY DEFAULT AS IDENTITY""" } else { """""" } } NOT NULL,
                  |""" } }""" } }    PRIMARY KEY (${model.primaryKeyColumn.columnName})
          |);
          |
        """.trimMargin(marginPrefix = "|")
    }

    override fun filePath(model: DbTableModel): String {
      return "R__schema_${model.tableName}.sql"
    }
}