package senegai.codegen.renderer.model.db

import senegai.codegen.renderer.model.NameCase

/**
 * One column of a [DbTableModel], storing exactly one attribute of the item.
 *
 * The [columnName] is a SQL identifier and therefore a plain string, either declared by the
 * `dbItem` of the item or derived from the [attributeName].
 */
data class DbColumnModel(
    val attributeName: NameCase,
    val columnName: String,
    val sqlType: DbSqlType,
    val isNullable: Boolean,
    val isPrimaryKey: Boolean,
) {
    val isJsonb: Boolean = sqlType == DbSqlType.JSONB

    /**
     * Whether the database hands out the value of this column, i.e. it is an integer primary key.
     * Such a column has to be declared `GENERATED BY DEFAULT AS IDENTITY` — never `ALWAYS`, as the
     * repository writes the key explicitly in its INSERT — because the `nextId()` of the
     * repository reads exactly the sequence PostgreSQL creates for an identity column.
     */
    val isIdentity: Boolean = isPrimaryKey && sqlType == DbSqlType.INTEGER
}
